export {default as Description} from './Description'
export {default as Details} from './Details'
export {default as Dates} from './Dates'
export {default as Location} from './Location'
export {default as Prices} from './Prices'
export {default as Amenities} from './Amenities'