import React from "react";
import Card from "./Card";

const data = [
	{
	  "id": 1108690,
	  "listing_url": "https://www.airbnb.com/rooms/1108690",
	  "scrape_id": 20150717184329,
	  "last_scraped": "2015-07-18",
	  "name": "Just 200m from Acropolis, Athens",
	  "summary": "",
	  "space": "Sunny & Quiet apartment  at the first floor in a beauty full building. Just 100 meters from Acropolis & 30 meters from the Acropolis Musuem. Bedroom with double futon bed, a kitchen, wireless internet, landline and a confortable bathroom.  The flat is able to host up to 3 accommodates. Alll this just around the corner of the new Acropolis musuem.that leads to Plaka Area,Irodeion theatre and Thision. Plaka is the area under the stone hill of Acropolis full with restaurants which serve delicious traditional food. Erodeion is an ancient greek theatre where concerts and theater performances taking place. Thision area is also very close to the apartment.Thision is well known for its bars and restaurants.What is more, the area is very well connected not only with the center of the town but also with the sea. Metro Acropolis is only ! 50 meters from the flat.Buses and tram are also very close. If you have any questions,do not hesitate to contact me.",
	  "description": "Sunny & Quiet apartment  at the first floor in a beauty full building. Just 100 meters from Acropolis & 30 meters from the Acropolis Musuem. Bedroom with double futon bed, a kitchen, wireless internet, landline and a confortable bathroom.  The flat is able to host up to 3 accommodates. Alll this just around the corner of the new Acropolis musuem.that leads to Plaka Area,Irodeion theatre and Thision. Plaka is the area under the stone hill of Acropolis full with restaurants which serve delicious traditional food. Erodeion is an ancient greek theatre where concerts and theater performances taking place. Thision area is also very close to the apartment.Thision is well known for its bars and restaurants.What is more, the area is very well connected not only with the center of the town but also with the sea. Metro Acropolis is only ! 50 meters from the flat.Buses and tram are also very close. If you have any questions,do not hesitate to contact me.",
	  "experiences_offered": "none",
	  "neighborhood_overview": "",
	  "notes": "",
	  "transit": "",
	  "thumbnail_url": "https://a0.muscache.com/ac/pictures/19034905/6982ee6c_original.jpg?interpolation=lanczos-none&size=small&output-format=jpg&output-quality=70",
	  "medium_url": "https://a0.muscache.com/ac/pictures/19034905/6982ee6c_original.jpg?interpolation=lanczos-none&size=medium&output-format=jpg&output-quality=70",
	  "picture_url": "https://a0.muscache.com/ac/pictures/19034905/6982ee6c_original.jpg?interpolation=lanczos-none&size=large_cover&output-format=jpg&output-quality=70",
	  "xl_picture_url": "https://a0.muscache.com/ac/pictures/19034905/6982ee6c_original.jpg?interpolation=lanczos-none&size=x_large_cover&output-format=jpg&output-quality=70",
	  "host_id": 2436598,
	  "host_url": "https://www.airbnb.com/users/show/2436598",
	  "host_name": "Ektoras",
	  "host_since": "2012-05-22",
	  "host_location": "Athens, Attica, Greece",
	  "host_about": "I love music, shadow, sea , sports & the theater.",
	  "host_response_time": "within an hour",
	  "host_response_rate": "95%",
	  "host_acceptance_rate": "98%",
	  "host_is_superhost": "f",
	  "host_thumbnail_url": "https://a1.muscache.com/ac/users/2436598/profile_pic/1384177608/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=50:*&output-format=jpg&output-quality=70",
	  "host_picture_url": "https://a1.muscache.com/ac/users/2436598/profile_pic/1384177608/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=225:*&output-format=jpg&output-quality=70",
	  "host_neighbourhood": "",
	  "host_listings_count": 2,
	  "host_total_listings_count": 2,
	  "host_verifications": "['email', 'phone', 'reviews']",
	  "host_has_profile_pic": "t",
	  "host_identity_verified": "f",
	  "street": "Chatzichristou, Athens, Attica 117 42, Greece",
	  "neighbourhood": "",
	  "neighbourhood_cleansed": "ΑΚΡΟΠΟΛΗ",
	  "neighbourhood_group_cleansed": "",
	  "city": "Athens",
	  "state": "Attica",
	  "zipcode": "117 42",
	  "market": "Athens",
	  "country_code": "GR",
	  "country": "Greece",
	  "latitude": 37.968869919951636,
	  "longitude": 23.728969555787607,
	  "is_location_exact": "t",
	  "property_type": "Apartment",
	  "room_type": "Entire home/apt",
	  "accommodates": 2,
	  "bathrooms": 1,
	  "bedrooms": 1,
	  "beds": 1,
	  "bed_type": "Real Bed",
	  "amenities": "{Internet,\"Wireless Internet\",\"Air Conditioning\",Kitchen,\"Elevator in Building\",Heating,\"Family/Kid Friendly\",Essentials,Shampoo}",
	  "square_feet": "",
	  "price": "$42.00",
	  "weekly_price": "",
	  "monthly_price": "",
	  "security_deposit": "",
	  "cleaning_fee": "",
	  "guests_included": 1,
	  "extra_people": "$17.00",
	  "minimum_nights": 1,
	  "maximum_nights": 365,
	  "calendar_updated": "3 days ago",
	  "has_availability": "t",
	  "availability_30": 10,
	  "availability_60": 34,
	  "availability_90": 64,
	  "availability_365": 336,
	  "calendar_last_scraped": "2015-07-18",
	  "number_of_reviews": 189,
	  "first_review": "2013-05-15",
	  "last_review": "2015-07-13",
	  "review_scores_rating": 86,
	  "review_scores_accuracy": 9,
	  "review_scores_cleanliness": 8,
	  "review_scores_checkin": 9,
	  "review_scores_communication": 10,
	  "review_scores_location": 10,
	  "review_scores_value": 9,
	  "requires_license": "t",
	  "license": "",
	  "jurisdiction_names": "",
	  "instant_bookable": "f",
	  "cancellation_policy": "strict",
	  "require_guest_profile_picture": "t",
	  "require_guest_phone_verification": "t",
	  "calculated_host_listings_count": 2,
	  "reviews_per_month": 7.13
	},
	{
	  "id": 1286210,
	  "listing_url": "https://www.airbnb.com/rooms/1286210",
	  "scrape_id": 20150717184329,
	  "last_scraped": "2015-07-18",
	  "name": "Zen space near center of Athens",
	  "summary": "",
	  "space": "JUST REFURBISHED - BRAND NEW APARTMENT. Very earthly energy. It is situated on the ground floor of a building. So...a zen apartment near the center of Athens. It is situated only fourty minutes from Athens airport by metro (no change is required). Once you get off at the metro stop Ambelokipi, you walk  minutes and voila!!! Three metro stops more and you will find yourselves in the center of Athens.  Back to zen.....it is a one bedroom apartment with a small dinning room and a living room.  The main glass wall provides a unique lighting throughout the day. At night the street light gives an overall warm glow to the space. A kitchen door leads to a small courtyard. At night the courtyard lights give a depth to the entire space. There is a mini market open from 10am to 12 midnight which can accommodate all your needs. There is also an excellent restaurant nearby where one can enjoy a fine lunch or a relaxing dinner. A less pricy restaurant is situated just across the street.",
	  "description": "JUST REFURBISHED - BRAND NEW APARTMENT. Very earthly energy. It is situated on the ground floor of a building. So...a zen apartment near the center of Athens. It is situated only fourty minutes from Athens airport by metro (no change is required). Once you get off at the metro stop Ambelokipi, you walk  minutes and voila!!! Three metro stops more and you will find yourselves in the center of Athens.  Back to zen.....it is a one bedroom apartment with a small dinning room and a living room.  The main glass wall provides a unique lighting throughout the day. At night the street light gives an overall warm glow to the space. A kitchen door leads to a small courtyard. At night the courtyard lights give a depth to the entire space. There is a mini market open from 10am to 12 midnight which can accommodate all your needs. There is also an excellent restaurant nearby where one can enjoy a fine lunch or a relaxing dinner. A less pricy restaurant is situated just across the street.",
	  "experiences_offered": "none",
	  "neighborhood_overview": "",
	  "notes": "",
	  "transit": "",
	  "thumbnail_url": "https://a1.muscache.com/ac/pictures/19389554/a2ff7ebf_original.jpg?interpolation=lanczos-none&size=small&output-format=jpg&output-quality=70",
	  "medium_url": "https://a1.muscache.com/ac/pictures/19389554/a2ff7ebf_original.jpg?interpolation=lanczos-none&size=medium&output-format=jpg&output-quality=70",
	  "picture_url": "https://a1.muscache.com/ac/pictures/19389554/a2ff7ebf_original.jpg?interpolation=lanczos-none&size=large_cover&output-format=jpg&output-quality=70",
	  "xl_picture_url": "https://a1.muscache.com/ac/pictures/19389554/a2ff7ebf_original.jpg?interpolation=lanczos-none&size=x_large_cover&output-format=jpg&output-quality=70",
	  "host_id": 372161,
	  "host_url": "https://www.airbnb.com/users/show/372161",
	  "host_name": "Peter",
	  "host_since": "2011-02-01",
	  "host_location": "Athens, Attica, Greece",
	  "host_about": "Filmmaker and musician who loves to walk Athens. Currently enjoying a hot summer after a demanding short film. Please visit my website to know more about me.\n(website hidden)",
	  "host_response_time": "a few days or more",
	  "host_response_rate": "33%",
	  "host_acceptance_rate": "100%",
	  "host_is_superhost": "f",
	  "host_thumbnail_url": "https://a2.muscache.com/ac/users/372161/profile_pic/1296594728/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=50:*&output-format=jpg&output-quality=70",
	  "host_picture_url": "https://a2.muscache.com/ac/users/372161/profile_pic/1296594728/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=225:*&output-format=jpg&output-quality=70",
	  "host_neighbourhood": "",
	  "host_listings_count": 1,
	  "host_total_listings_count": 1,
	  "host_verifications": "['email', 'facebook', 'reviews']",
	  "host_has_profile_pic": "t",
	  "host_identity_verified": "f",
	  "street": "Vatheos, Athens, Attica 115 22, Greece",
	  "neighbourhood": "",
	  "neighbourhood_cleansed": "ΑΜΠΕΛΟΚΗΠΟΙ",
	  "neighbourhood_group_cleansed": "",
	  "city": "Athens",
	  "state": "Attica",
	  "zipcode": "115 22",
	  "market": "Athens",
	  "country_code": "GR",
	  "country": "Greece",
	  "latitude": 37.989954745633725,
	  "longitude": 23.758910281603455,
	  "is_location_exact": "t",
	  "property_type": "Apartment",
	  "room_type": "Entire home/apt",
	  "accommodates": 2,
	  "bathrooms": 1,
	  "bedrooms": 1,
	  "beds": 1,
	  "bed_type": "Real Bed",
	  "amenities": "{\"Wireless Internet\",Kitchen,\"Pets Allowed\",Heating,\"Family/Kid Friendly\",Washer}",
	  "square_feet": "",
	  "price": "$48.00",
	  "weekly_price": "$250.00",
	  "monthly_price": "$560.00",
	  "security_deposit": "",
	  "cleaning_fee": "$10.00",
	  "guests_included": 1,
	  "extra_people": "$0.00",
	  "minimum_nights": 1,
	  "maximum_nights": 1125,
	  "calendar_updated": "6 weeks ago",
	  "has_availability": "t",
	  "availability_30": 11,
	  "availability_60": 41,
	  "availability_90": 71,
	  "availability_365": 346,
	  "calendar_last_scraped": "2015-07-17",
	  "number_of_reviews": 4,
	  "first_review": "2013-12-14",
	  "last_review": "2015-07-05",
	  "review_scores_rating": 100,
	  "review_scores_accuracy": 10,
	  "review_scores_cleanliness": 10,
	  "review_scores_checkin": 10,
	  "review_scores_communication": 10,
	  "review_scores_location": 10,
	  "review_scores_value": 10,
	  "requires_license": "t",
	  "license": "",
	  "jurisdiction_names": "",
	  "instant_bookable": "f",
	  "cancellation_policy": "moderate",
	  "require_guest_profile_picture": "f",
	  "require_guest_phone_verification": "f",
	  "calculated_host_listings_count": 1,
	  "reviews_per_month": 0.21
	},
	{
	  "id": 918812,
	  "listing_url": "https://www.airbnb.com/rooms/918812",
	  "scrape_id": 20150717184329,
	  "last_scraped": "2015-07-18",
	  "name": "Athens Soul Apartments Plaka",
	  "summary": "",
	  "space": "This 30m2 flat on Frinihou str. is located in Plaka, the old part of the city, at the foot of the Acropolis in the heart of Athens. Frinihou str. is a quiet street very close to a main street which leads to the New Acropolis Museum. The flat is only 100m away from the “Acropolis” Metro station as well as the New Acropolis Museum. Very close -less than 50m away- the Dionisiou Aeropagitou pedestrian street starts which is considered one of the most beautiful pedestrian streets in Athens. It takes straight to the Herodou Attikou ancient theatre. The flat is in the semi-basement of a stately building with its own court aglaise. It overlooks the street and its really sunny and bright. The flat is fully furnished, beautifully decorated and equipped with a kitchen , air-conditioning , central heating, a telephone line and free Internet. It is a two person flat but there is plenty of room for a third person. Super offer Two bicycles at your disposal, to ride the historical part of Athens free",
	  "description": "This 30m2 flat on Frinihou str. is located in Plaka, the old part of the city, at the foot of the Acropolis in the heart of Athens. Frinihou str. is a quiet street very close to a main street which leads to the New Acropolis Museum. The flat is only 100m away from the “Acropolis” Metro station as well as the New Acropolis Museum. Very close -less than 50m away- the Dionisiou Aeropagitou pedestrian street starts which is considered one of the most beautiful pedestrian streets in Athens. It takes straight to the Herodou Attikou ancient theatre. The flat is in the semi-basement of a stately building with its own court aglaise. It overlooks the street and its really sunny and bright. The flat is fully furnished, beautifully decorated and equipped with a kitchen , air-conditioning , central heating, a telephone line and free Internet. It is a two person flat but there is plenty of room for a third person. Super offer Two bicycles at your disposal, to ride the historical part of Athens free",
	  "experiences_offered": "none",
	  "neighborhood_overview": "",
	  "notes": "",
	  "transit": "",
	  "thumbnail_url": "https://a1.muscache.com/ac/pictures/13462809/26642ff7_original.jpg?interpolation=lanczos-none&size=small&output-format=jpg&output-quality=70",
	  "medium_url": "https://a1.muscache.com/ac/pictures/13462809/26642ff7_original.jpg?interpolation=lanczos-none&size=medium&output-format=jpg&output-quality=70",
	  "picture_url": "https://a1.muscache.com/ac/pictures/13462809/26642ff7_original.jpg?interpolation=lanczos-none&size=large_cover&output-format=jpg&output-quality=70",
	  "xl_picture_url": "https://a1.muscache.com/ac/pictures/13462809/26642ff7_original.jpg?interpolation=lanczos-none&size=x_large_cover&output-format=jpg&output-quality=70",
	  "host_id": 4935030,
	  "host_url": "https://www.airbnb.com/users/show/4935030",
	  "host_name": "Dimitris",
	  "host_since": "2013-02-02",
	  "host_location": "Athens, Attica, Greece",
	  "host_about": "Hello! My name is Dimitris. You are welcome to come and stay at my apartments in Athens, Greece! If you have any questions, feel free to ask!",
	  "host_response_time": "within a few hours",
	  "host_response_rate": "100%",
	  "host_acceptance_rate": "100%",
	  "host_is_superhost": "f",
	  "host_thumbnail_url": "https://a0.muscache.com/ac/users/4935030/profile_pic/1359790474/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=50:*&output-format=jpg&output-quality=70",
	  "host_picture_url": "https://a0.muscache.com/ac/users/4935030/profile_pic/1359790474/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=225:*&output-format=jpg&output-quality=70",
	  "host_neighbourhood": "",
	  "host_listings_count": 2,
	  "host_total_listings_count": 2,
	  "host_verifications": "['email', 'phone', 'facebook', 'linkedin', 'reviews', 'jumio']",
	  "host_has_profile_pic": "t",
	  "host_identity_verified": "t",
	  "street": "Frinichou, Athens, Attica 105 58, Greece",
	  "neighbourhood": "",
	  "neighbourhood_cleansed": "ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ",
	  "neighbourhood_group_cleansed": "",
	  "city": "Athens",
	  "state": "Attica",
	  "zipcode": "105 58",
	  "market": "Athens",
	  "country_code": "GR",
	  "country": "Greece",
	  "latitude": 37.969859435055255,
	  "longitude": 23.731203858464916,
	  "is_location_exact": "t",
	  "property_type": "Apartment",
	  "room_type": "Entire home/apt",
	  "accommodates": 2,
	  "bathrooms": 1,
	  "bedrooms": 1,
	  "beds": 1,
	  "bed_type": "Real Bed",
	  "amenities": "{Internet,\"Wireless Internet\",\"Air Conditioning\",Kitchen,Heating}",
	  "square_feet": 323,
	  "price": "$40.00",
	  "weekly_price": "",
	  "monthly_price": "",
	  "security_deposit": "",
	  "cleaning_fee": "$10.00",
	  "guests_included": 1,
	  "extra_people": "$0.00",
	  "minimum_nights": 3,
	  "maximum_nights": 60,
	  "calendar_updated": "3 weeks ago",
	  "has_availability": "t",
	  "availability_30": 4,
	  "availability_60": 7,
	  "availability_90": 12,
	  "availability_365": 224,
	  "calendar_last_scraped": "2015-07-18",
	  "number_of_reviews": 102,
	  "first_review": "2013-03-25",
	  "last_review": "2015-07-05",
	  "review_scores_rating": 95,
	  "review_scores_accuracy": 10,
	  "review_scores_cleanliness": 9,
	  "review_scores_checkin": 10,
	  "review_scores_communication": 10,
	  "review_scores_location": 10,
	  "review_scores_value": 10,
	  "requires_license": "t",
	  "license": "",
	  "jurisdiction_names": "",
	  "instant_bookable": "f",
	  "cancellation_policy": "moderate",
	  "require_guest_profile_picture": "f",
	  "require_guest_phone_verification": "t",
	  "calculated_host_listings_count": 2,
	  "reviews_per_month": 3.62
	},
	{
		"id": 1116076,
		"listing_url": "https://www.airbnb.com/rooms/1116076",
		"scrape_id": 20150717184329,
		"last_scraped": "2015-07-18",
		"name": "Central Location",
		"summary": "",
		"space": "Spacious first floor 2 bedroom apartment perfectly located for sightseeing, transport and shopping. Fully self contained with an eat in kitchen. The apartment is large with 2 separate bedrooms to the living area. The second bedroom is the 'meditation room and library' photo where we have 2 collapsible single beds separate to the library area. The apartment is on the first floor with no lift. Central to all that Athens has to offer with easy access to transport, including Monastiraki station, buses and taxis. Convenient to cafes and restaurants with a cafe/bar opposite serving home made local food and authentic Greek coffee and wine, among many other things... or just grab a takeaway and sit on your balcony and watch the Athens activity go by. The apartment block is a modernized Art Deco four storey apartment block central to the Plakka, the markets, museums and Evripidou Street, the designers' shopping strip. You'll just love being totally in the thick of it all!",
		"description": "Spacious first floor 2 bedroom apartment perfectly located for sightseeing, transport and shopping. Fully self contained with an eat in kitchen. The apartment is large with 2 separate bedrooms to the living area. The second bedroom is the 'meditation room and library' photo where we have 2 collapsible single beds separate to the library area. The apartment is on the first floor with no lift. Central to all that Athens has to offer with easy access to transport, including Monastiraki station, buses and taxis. Convenient to cafes and restaurants with a cafe/bar opposite serving home made local food and authentic Greek coffee and wine, among many other things... or just grab a takeaway and sit on your balcony and watch the Athens activity go by. The apartment block is a modernized Art Deco four storey apartment block central to the Plakka, the markets, museums and Evripidou Street, the designers' shopping strip. You'll just love being totally in the thick of it all!",
		"experiences_offered": "none",
		"neighborhood_overview": "",
		"notes": "",
		"transit": "",
		"thumbnail_url": "https://a1.muscache.com/ac/pictures/16886510/26f68bb3_original.jpg?interpolation=lanczos-none&size=small&output-format=jpg&output-quality=70",
		"medium_url": "https://a1.muscache.com/ac/pictures/16886510/26f68bb3_original.jpg?interpolation=lanczos-none&size=medium&output-format=jpg&output-quality=70",
		"picture_url": "https://a1.muscache.com/ac/pictures/16886510/26f68bb3_original.jpg?interpolation=lanczos-none&size=large_cover&output-format=jpg&output-quality=70",
		"xl_picture_url": "https://a1.muscache.com/ac/pictures/16886510/26f68bb3_original.jpg?interpolation=lanczos-none&size=x_large_cover&output-format=jpg&output-quality=70",
		"host_id": 6125356,
		"host_url": "https://www.airbnb.com/users/show/6125356",
		"host_name": "Lenka & Tamara",
		"host_since": "2013-04-28",
		"host_location": "Athens, Attica, Greece",
		"host_about": "Tamara and I have been friends for a number of years. We both run our own businesses.  Mine is in interior design and Tamara teaches sewing. We both love the beach and being at opposite ends of the hemisphere when I’m swimming Tamara is in a woolen coat and when Tamara is swimming I’m in my neck to knees.  In Tamara’s spare time you’ll find her frolicking on one of Athens’ beautiful beaches. If you are lucky she may even share with you her special swimming spots!",
		"host_response_time": "within a day",
		"host_response_rate": "80%",
		"host_acceptance_rate": "100%",
		"host_is_superhost": "f",
		"host_thumbnail_url": "https://a1.muscache.com/ac/users/6125356/profile_pic/1367147857/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=50:*&output-format=jpg&output-quality=70",
		"host_picture_url": "https://a1.muscache.com/ac/users/6125356/profile_pic/1367147857/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=225:*&output-format=jpg&output-quality=70",
		"host_neighbourhood": "",
		"host_listings_count": 1,
		"host_total_listings_count": 1,
		"host_verifications": "['email', 'phone', 'reviews']",
		"host_has_profile_pic": "t",
		"host_identity_verified": "f",
		"street": "Agathonos, Athens, Attica 105 51, Greece",
		"neighbourhood": "",
		"neighbourhood_cleansed": "ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ",
		"neighbourhood_group_cleansed": "",
		"city": "Athens",
		"state": "Attica",
		"zipcode": "105 51",
		"market": "Athens",
		"country_code": "GR",
		"country": "Greece",
		"latitude": 37.97909305983615,
		"longitude": 23.728316935867685,
		"is_location_exact": "t",
		"property_type": "Apartment",
		"room_type": "Entire home/apt",
		"accommodates": 4,
		"bathrooms": 1.5,
		"bedrooms": 2,
		"beds": 1,
		"bed_type": "Real Bed",
		"amenities": "{Kitchen,\"Buzzer/Wireless Intercom\",Heating,\"Family/Kid Friendly\",Washer}",
		"square_feet": 0,
		"price": "$70.00",
		"weekly_price": "$400.00",
		"monthly_price": "$1,800.00",
		"security_deposit": "",
		"cleaning_fee": "$30.00",
		"guests_included": 2,
		"extra_people": "$10.00",
		"minimum_nights": 2,
		"maximum_nights": 1125,
		"calendar_updated": "2 weeks ago",
		"has_availability": "t",
		"availability_30": 9,
		"availability_60": 20,
		"availability_90": 22,
		"availability_365": 198,
		"calendar_last_scraped": "2015-07-18",
		"number_of_reviews": 37,
		"first_review": "2013-06-04",
		"last_review": "2015-06-20",
		"review_scores_rating": 95,
		"review_scores_accuracy": 10,
		"review_scores_cleanliness": 9,
		"review_scores_checkin": 10,
		"review_scores_communication": 10,
		"review_scores_location": 10,
		"review_scores_value": 9,
		"requires_license": "t",
		"license": "",
		"jurisdiction_names": "",
		"instant_bookable": "f",
		"cancellation_policy": "strict",
		"require_guest_profile_picture": "f",
		"require_guest_phone_verification": "f",
		"calculated_host_listings_count": 1,
		"reviews_per_month": 1.43
	},
	{
	"id": 134273,
	"listing_url": "https://www.airbnb.com/rooms/134273",
	"scrape_id": 20150717184329,
	"last_scraped": "2015-07-18",
	"name": "Renovated old house",
	"summary": "",
	"space": "Old neoclassic architecture two level store. One floor (level) is for rent. Pedestrian area !",
	"description": "Old neoclassic architecture two level store. One floor (level) is for rent. Pedestrian area !",
	"experiences_offered": "none",
	"neighborhood_overview": "",
	"notes": "",
	"transit": "",
	"thumbnail_url": "https://a2.muscache.com/ac/pictures/852527/60a0e428_original.jpg?interpolation=lanczos-none&size=small&output-format=jpg&output-quality=70",
	"medium_url": "https://a2.muscache.com/ac/pictures/852527/60a0e428_original.jpg?interpolation=lanczos-none&size=medium&output-format=jpg&output-quality=70",
	"picture_url": "https://a2.muscache.com/ac/pictures/852527/60a0e428_original.jpg?interpolation=lanczos-none&size=large_cover&output-format=jpg&output-quality=70",
	"xl_picture_url": "https://a2.muscache.com/ac/pictures/852527/60a0e428_original.jpg?interpolation=lanczos-none&size=x_large_cover&output-format=jpg&output-quality=70",
	"host_id": 659132,
	"host_url": "https://www.airbnb.com/users/show/659132",
	"host_name": "Kostas",
	"host_since": "2011-06-03",
	"host_location": "GR",
	"host_about": "",
	"host_response_time": "N/A",
	"host_response_rate": "N/A",
	"host_acceptance_rate": "N/A",
	"host_is_superhost": "f",
	"host_thumbnail_url": "https://a2.muscache.com/defaults/user_pic-50x50.png?v=2",
	"host_picture_url": "https://a2.muscache.com/defaults/user_pic-225x225.png?v=2",
	"host_neighbourhood": "",
	"host_listings_count": 1,
	"host_total_listings_count": 1,
	"host_verifications": "['email']",
	"host_has_profile_pic": "f",
	"host_identity_verified": "f",
	"street": "Paramythias, Athens, Attica 10435, Greece",
	"neighbourhood": "",
	"neighbourhood_cleansed": "ΚΕΡΑΜΕΙΚΟΣ",
	"neighbourhood_group_cleansed": "",
	"city": "Athens",
	"state": "Attica",
	"zipcode": 10435,
	"market": "Athens",
	"country_code": "GR",
	"country": "Greece",
	"latitude": 37.98164980565811,
	"longitude": 23.71429216602147,
	"is_location_exact": "t",
	"property_type": "House",
	"room_type": "Entire home/apt",
	"accommodates": 4,
	"bathrooms": "",
	"bedrooms": 2,
	"beds": 1,
	"bed_type": "Real Bed",
	"amenities": {},
	"square_feet": "",
	"price": "$30.00",
	"weekly_price": "$220.00",
	"monthly_price": "$850.00",
	"security_deposit": "",
	"cleaning_fee": "",
	"guests_included": 1,
	"extra_people": "$0.00",
	"minimum_nights": 10,
	"maximum_nights": 730,
	"calendar_updated": "4 months ago",
	"has_availability": "t",
	"availability_30": 30,
	"availability_60": 60,
	"availability_90": 90,
	"availability_365": 365,
	"calendar_last_scraped": "2015-07-18",
	"number_of_reviews": 0,
	"first_review": "",
	"last_review": "",
	"review_scores_rating": "",
	"review_scores_accuracy": "",
	"review_scores_cleanliness": "",
	"review_scores_checkin": "",
	"review_scores_communication": "",
	"review_scores_location": "",
	"review_scores_value": "",
	"requires_license": "t",
	"license": "",
	"jurisdiction_names": "",
	"instant_bookable": "f",
	"cancellation_policy": "flexible",
	"require_guest_profile_picture": "f",
	"require_guest_phone_verification": "f",
	"calculated_host_listings_count": 1,
	"reviews_per_month": ""
	},
	{
	"id": 1824675,
	"listing_url": "https://www.airbnb.com/rooms/1824675",
	"scrape_id": 20150717184329,
	"last_scraped": "2015-07-18",
	"name": "Your room in the perfect area",
	"summary": "",
	"space": "The house is located in one of the oldest and picturesque neighbourghoods of the center of Athens, called Ano Petralona. It is situated at the feet of filopappou hill right across the Acropolis. The house was built in the late 1950's and has remained since with its high ceilings and the traditional mosaique floors and a roof garden under the Attica sky.The living room is surrounded by 5 rooms, one fully equipped kitchen, a bathroom with a bath tub and a toilet, and a small w.c.  I share the house with my flatmate Panos and we both enjoy hosting and meeting new people from all over the world.  You will have at your disposal a large bedroom with a double bed and a private sitting room with eastern orientation and great shinning mornings! The kitchen is fully equipped and functional as is the bathroom.  Behind the kitchen a spiral ladder leads you to the roof garden that you can enjoy day and night and is the perfect place to relax.  The Ano Petralona is a lively neighbourhood, very close",
	"description": "The house is located in one of the oldest and picturesque neighbourghoods of the center of Athens, called Ano Petralona. It is situated at the feet of filopappou hill right across the Acropolis. The house was built in the late 1950's and has remained since with its high ceilings and the traditional mosaique floors and a roof garden under the Attica sky.The living room is surrounded by 5 rooms, one fully equipped kitchen, a bathroom with a bath tub and a toilet, and a small w.c.  I share the house with my flatmate Panos and we both enjoy hosting and meeting new people from all over the world.  You will have at your disposal a large bedroom with a double bed and a private sitting room with eastern orientation and great shinning mornings! The kitchen is fully equipped and functional as is the bathroom.  Behind the kitchen a spiral ladder leads you to the roof garden that you can enjoy day and night and is the perfect place to relax.  The Ano Petralona is a lively neighbourhood, very close",
	"experiences_offered": "none",
	"neighborhood_overview": "",
	"notes": "",
	"transit": "",
	"thumbnail_url": "https://a0.muscache.com/ac/pictures/26186478/ce86821d_original.jpg?interpolation=lanczos-none&size=small&output-format=jpg&output-quality=70",
	"medium_url": "https://a0.muscache.com/ac/pictures/26186478/ce86821d_original.jpg?interpolation=lanczos-none&size=medium&output-format=jpg&output-quality=70",
	"picture_url": "https://a0.muscache.com/ac/pictures/26186478/ce86821d_original.jpg?interpolation=lanczos-none&size=large_cover&output-format=jpg&output-quality=70",
	"xl_picture_url": "https://a0.muscache.com/ac/pictures/26186478/ce86821d_original.jpg?interpolation=lanczos-none&size=x_large_cover&output-format=jpg&output-quality=70",
	"host_id": 9550291,
	"host_url": "https://www.airbnb.com/users/show/9550291",
	"host_name": "Christos",
	"host_since": "2013-10-21",
	"host_location": "Athens, Attica, Greece",
	"host_about": "I will be happy to help you discover Athens.",
	"host_response_time": "within a few hours",
	"host_response_rate": "100%",
	"host_acceptance_rate": "100%",
	"host_is_superhost": "f",
	"host_thumbnail_url": "https://a2.muscache.com/ac/users/9550291/profile_pic/1383428742/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=50:*&output-format=jpg&output-quality=70",
	"host_picture_url": "https://a2.muscache.com/ac/users/9550291/profile_pic/1383428742/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=225:*&output-format=jpg&output-quality=70",
	"host_neighbourhood": "",
	"host_listings_count": 1,
	"host_total_listings_count": 1,
	"host_verifications": "['email', 'phone', 'reviews']",
	"host_has_profile_pic": "t",
	"host_identity_verified": "f",
	"street": "Dimofontos, Athens, Attica 118 52, Greece",
	"neighbourhood": "",
	"neighbourhood_cleansed": "ΠΕΤΡΑΛΩΝΑ",
	"neighbourhood_group_cleansed": "",
	"city": "Athens",
	"state": "Attica",
	"zipcode": "118 52",
	"market": "Athens",
	"country_code": "GR",
	"country": "Greece",
	"latitude": 37.972306424466325,
	"longitude": 23.712209737541663,
	"is_location_exact": "f",
	"property_type": "House",
	"room_type": "Private room",
	"accommodates": 5,
	"bathrooms": 1.5,
	"bedrooms": 1,
	"beds": 3,
	"bed_type": "Real Bed",
	"amenities": "{Internet,\"Wireless Internet\",Kitchen,\"Smoking Allowed\",\"Pets Allowed\",Heating,\"Family/Kid Friendly\",Washer,Essentials}",
	"square_feet": "",
	"price": "$45.00",
	"weekly_price": "",
	"monthly_price": "",
	"security_deposit": "",
	"cleaning_fee": "$15.00",
	"guests_included": 2,
	"extra_people": "$15.00",
	"minimum_nights": 1,
	"maximum_nights": 60,
	"calendar_updated": "a week ago",
	"has_availability": "t",
	"availability_30": 3,
	"availability_60": 13,
	"availability_90": 26,
	"availability_365": 193,
	"calendar_last_scraped": "2015-07-18",
	"number_of_reviews": 129,
	"first_review": "2013-11-05",
	"last_review": "2015-07-14",
	"review_scores_rating": 94,
	"review_scores_accuracy": 10,
	"review_scores_cleanliness": 10,
	"review_scores_checkin": 10,
	"review_scores_communication": 10,
	"review_scores_location": 9,
	"review_scores_value": 10,
	"requires_license": "t",
	"license": "",
	"jurisdiction_names": "",
	"instant_bookable": "f",
	"cancellation_policy": "moderate",
	"require_guest_profile_picture": "f",
	"require_guest_phone_verification": "f",
	"calculated_host_listings_count": 1,
	"reviews_per_month": 6.23
	},
	{
	"id": 360940,
	"listing_url": "https://www.airbnb.com/rooms/360940",
	"scrape_id": 20150717184329,
	"last_scraped": "2015-07-18",
	"name": "Vintage Design Flat downtown!",
	"summary": "",
	"space": "the.flat |  A high-ceilinged penthouse of a 50s residential building in the centre of Athens, right in front of Kalliga Square and opposite the Theatre Library. \"the.flat\" is a personal space renovated in style a few months ago that kept its urban identity and now offers its space for a vintage short term stay to visitors from around the world.  \"the.flat\" has a large living room and dining room for 6, two large bedrooms, kitchen (refrigerator, mini oven, coffee maker and kettle), a bathroom with a bathtub, a w.c. and a large veranda. Provides free wi-fi. Central heating is provided by the building.  walking distances:  1 minute from Patission Ave (28th October Ave) /  6 minutes from Aghios Nikolaos Metro station /  12 minutes from Victoria Metro Station /  12 minutes from National Archaeological Museum /  20 minutes from Omonia Square.  One minute from two supermarkets, grocery stores, a National Bank branch, drugstores, parking stations and right in front of Karamanlaki Square.  Pati",
	"description": "the.flat |  A high-ceilinged penthouse of a 50s residential building in the centre of Athens, right in front of Kalliga Square and opposite the Theatre Library. \"the.flat\" is a personal space renovated in style a few months ago that kept its urban identity and now offers its space for a vintage short term stay to visitors from around the world.  \"the.flat\" has a large living room and dining room for 6, two large bedrooms, kitchen (refrigerator, mini oven, coffee maker and kettle), a bathroom with a bathtub, a w.c. and a large veranda. Provides free wi-fi. Central heating is provided by the building.  walking distances:  1 minute from Patission Ave (28th October Ave) /  6 minutes from Aghios Nikolaos Metro station /  12 minutes from Victoria Metro Station /  12 minutes from National Archaeological Museum /  20 minutes from Omonia Square.  One minute from two supermarkets, grocery stores, a National Bank branch, drugstores, parking stations and right in front of Karamanlaki Square.  Pati",
	"experiences_offered": "none",
	"neighborhood_overview": "",
	"notes": "",
	"transit": "",
	"thumbnail_url": "https://a1.muscache.com/ac/pictures/4035997/1f7bae95_original.jpg?interpolation=lanczos-none&size=small&output-format=jpg&output-quality=70",
	"medium_url": "https://a1.muscache.com/ac/pictures/4035997/1f7bae95_original.jpg?interpolation=lanczos-none&size=medium&output-format=jpg&output-quality=70",
	"picture_url": "https://a1.muscache.com/ac/pictures/4035997/1f7bae95_original.jpg?interpolation=lanczos-none&size=large_cover&output-format=jpg&output-quality=70",
	"xl_picture_url": "https://a1.muscache.com/ac/pictures/4035997/1f7bae95_original.jpg?interpolation=lanczos-none&size=x_large_cover&output-format=jpg&output-quality=70",
	"host_id": 1824707,
	"host_url": "https://www.airbnb.com/users/show/1824707",
	"host_name": "Dimitrios",
	"host_since": "2012-02-28",
	"host_location": "Athens, Attica, Greece",
	"host_about": "I live in Athens! Spent last years in London, New York and all over Italy. I ve been an artist since the day I remember myself. I work as a theatre director and a performer. I love interior design, european litterature and jazz music. I spend my rare day-offs with friends and family. Enjoy meeting new people and cultures. So be my guest!",
	"host_response_time": "within a few hours",
	"host_response_rate": "80%",
	"host_acceptance_rate": "100%",
	"host_is_superhost": "f",
	"host_thumbnail_url": "https://a1.muscache.com/ac/users/1824707/profile_pic/1341009112/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=50:*&output-format=jpg&output-quality=70",
	"host_picture_url": "https://a1.muscache.com/ac/users/1824707/profile_pic/1341009112/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=225:*&output-format=jpg&output-quality=70",
	"host_neighbourhood": "",
	"host_listings_count": 1,
	"host_total_listings_count": 1,
	"host_verifications": "['email', 'phone', 'reviews']",
	"host_has_profile_pic": "t",
	"host_identity_verified": "f",
	"street": "Karamanlaki, Athens, Attica 11253, Greece",
	"neighbourhood": "",
	"neighbourhood_cleansed": "ΠΛΑΤΕΙΑ ΑΜΕΡΙΚΗΣ",
	"neighbourhood_group_cleansed": "",
	"city": "Athens",
	"state": "Attica",
	"zipcode": 11253,
	"market": "Athens",
	"country_code": "GR",
	"country": "Greece",
	"latitude": 38.00642361118162,
	"longitude": 23.73224172508163,
	"is_location_exact": "t",
	"property_type": "Apartment",
	"room_type": "Entire home/apt",
	"accommodates": 4,
	"bathrooms": 1.5,
	"bedrooms": 2,
	"beds": 3,
	"bed_type": "Real Bed",
	"amenities": "{TV,\"Wireless Internet\",\"Air Conditioning\",Kitchen,\"Elevator in Building\",\"Family/Kid Friendly\"}",
	"square_feet": 1292,
	"price": "$65.00",
	"weekly_price": "",
	"monthly_price": "",
	"security_deposit": "",
	"cleaning_fee": "$30.00",
	"guests_included": 2,
	"extra_people": "$15.00",
	"minimum_nights": 2,
	"maximum_nights": 1125,
	"calendar_updated": "9 months ago",
	"has_availability": "t",
	"availability_30": 30,
	"availability_60": 60,
	"availability_90": 90,
	"availability_365": 365,
	"calendar_last_scraped": "2015-07-17",
	"number_of_reviews": 16,
	"first_review": "2013-08-14",
	"last_review": "2015-06-18",
	"review_scores_rating": 94,
	"review_scores_accuracy": 9,
	"review_scores_cleanliness": 9,
	"review_scores_checkin": 10,
	"review_scores_communication": 10,
	"review_scores_location": 8,
	"review_scores_value": 10,
	"requires_license": "t",
	"license": "",
	"jurisdiction_names": "",
	"instant_bookable": "f",
	"cancellation_policy": "strict",
	"require_guest_profile_picture": "f",
	"require_guest_phone_verification": "f",
	"calculated_host_listings_count": 1,
	"reviews_per_month": 0.68
	},
	{
	"id": 448963,
	"listing_url": "https://www.airbnb.com/rooms/448963",
	"scrape_id": 20150717184329,
	"last_scraped": "2015-07-18",
	"name": "Beautiful Apartment Central Athens",
	"summary": "",
	"space": "This beautiful apartment in Central Athens is in the area of Victoria and only a short walk from the metro and Square.   The apartment has two double bedrooms with balconies, 1 bathroom with a Jakoozi, a spacious open plan fully fitted kitchen, dining and living room adjacent to a large bacony. This apartment has been stylishly renovated and has wooden floors throughout, modern kitchen with all the necessary white goods, wash room with machine and dryer, air conditioning throughout and central heating.  There is also an office area, stereo and TV.  A small storage room is included.  The apartment sleeps up to 6 as there is a sofa bed and camp bed .  Victoria is very close to the  Archaelogical Museum, shopping Mall and busy high street servicing a range of products.  Victoria Square plays host to a number of very good café bars and restaurants.  The apartment is on a pedestrian road creating a quiet environment for an Athens flat.  There is a famous traditional restaurant in the same s",
	"description": "This beautiful apartment in Central Athens is in the area of Victoria and only a short walk from the metro and Square.   The apartment has two double bedrooms with balconies, 1 bathroom with a Jakoozi, a spacious open plan fully fitted kitchen, dining and living room adjacent to a large bacony. This apartment has been stylishly renovated and has wooden floors throughout, modern kitchen with all the necessary white goods, wash room with machine and dryer, air conditioning throughout and central heating.  There is also an office area, stereo and TV.  A small storage room is included.  The apartment sleeps up to 6 as there is a sofa bed and camp bed .  Victoria is very close to the  Archaelogical Museum, shopping Mall and busy high street servicing a range of products.  Victoria Square plays host to a number of very good café bars and restaurants.  The apartment is on a pedestrian road creating a quiet environment for an Athens flat.  There is a famous traditional restaurant in the same s",
	"experiences_offered": "none",
	"neighborhood_overview": "",
	"notes": "",
	"transit": "",
	"thumbnail_url": "https://a1.muscache.com/ac/pictures/5210808/7cf4a030_original.jpg?interpolation=lanczos-none&size=small&output-format=jpg&output-quality=70",
	"medium_url": "https://a1.muscache.com/ac/pictures/5210808/7cf4a030_original.jpg?interpolation=lanczos-none&size=medium&output-format=jpg&output-quality=70",
	"picture_url": "https://a1.muscache.com/ac/pictures/5210808/7cf4a030_original.jpg?interpolation=lanczos-none&size=large_cover&output-format=jpg&output-quality=70",
	"xl_picture_url": "https://a1.muscache.com/ac/pictures/5210808/7cf4a030_original.jpg?interpolation=lanczos-none&size=x_large_cover&output-format=jpg&output-quality=70",
	"host_id": 2229246,
	"host_url": "https://www.airbnb.com/users/show/2229246",
	"host_name": "Nikos",
	"host_since": "2012-04-26",
	"host_location": "Athens, Attica, Greece",
	"host_about": "I am married with a little girl called Nefeli.  I am an Engineer, study English as a foreign language and love travelling to new places.",
	"host_response_time": "N/A",
	"host_response_rate": "N/A",
	"host_acceptance_rate": "N/A",
	"host_is_superhost": "f",
	"host_thumbnail_url": "https://a0.muscache.com/ac/users/2229246/profile_pic/1335458145/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=50:*&output-format=jpg&output-quality=70",
	"host_picture_url": "https://a0.muscache.com/ac/users/2229246/profile_pic/1335458145/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=225:*&output-format=jpg&output-quality=70",
	"host_neighbourhood": "",
	"host_listings_count": 1,
	"host_total_listings_count": 1,
	"host_verifications": "['email', 'phone']",
	"host_has_profile_pic": "t",
	"host_identity_verified": "f",
	"street": "Elpidos, Athens, Attica 10434, Greece",
	"neighbourhood": "",
	"neighbourhood_cleansed": "ΠΛΑΤΕΙΑ ΑΤΤΙΚΗΣ",
	"neighbourhood_group_cleansed": "",
	"city": "Athens",
	"state": "Attica",
	"zipcode": 10434,
	"market": "Athens",
	"country_code": "GR",
	"country": "Greece",
	"latitude": 37.99491920535935,
	"longitude": 23.731029860409894,
	"is_location_exact": "t",
	"property_type": "Apartment",
	"room_type": "Entire home/apt",
	"accommodates": 5,
	"bathrooms": "",
	"bedrooms": 2,
	"beds": "1",
	"bed_type": "Real Bed",
	"amenities": {},
	"square_feet": "",
	"price": "$95.00",
	"weekly_price": "$600.00",
	"monthly_price": "$2,000.00",
	"security_deposit": "",
	"cleaning_fee": "",
	"guests_included": 1,
	"extra_people": "$0.00",
	"minimum_nights": 7,
	"maximum_nights": 90,
	"calendar_updated": "39 months ago",
	"has_availability": "t",
	"availability_30": 30,
	"availability_60": 60,
	"availability_90": 90,
	"availability_365": 365,
	"calendar_last_scraped": "2015-07-18",
	"number_of_reviews": 0,
	"first_review": "",
	"last_review": "",
	"review_scores_rating": "",
	"review_scores_accuracy": "",
	"review_scores_cleanliness": "",
	"review_scores_checkin": "",
	"review_scores_communication": "",
	"review_scores_location": "",
	"review_scores_value": "",
	"requires_license": "t",
	"license": "",
	"jurisdiction_names": "",
	"instant_bookable": "f",
	"cancellation_policy": "flexible",
	"require_guest_profile_picture": "f",
	"require_guest_phone_verification": "f",
	"calculated_host_listings_count": 1,
	"reviews_per_month": ""
	},
  ];

const Cards = () => (
	<div className="flex flex-wrap">
		{data.map(({thumbnail_url, medium_url, price, room_type, beds, number_of_reviews, review_scores_rating,street, description,name,host_name,host_picture_url,amenities,accommodates,bathrooms,bedrooms,bed_type }, id) => (
			<Card key={id} id={id} thumbnail_url={thumbnail_url} medium_url={medium_url} price={price} room_type={room_type} beds={beds} number_of_reviews={number_of_reviews} review_scores_rating={review_scores_rating} street={street} description={description} name={name} host_name={host_name} host_picture_url={host_picture_url} amenities={amenities} accommodates={accommodates} bathrooms={bathrooms} bedrooms={bedrooms} bed_type={bed_type}/>
		))}
	</div>
);

export default Cards;

