import React from "react";
import Card from "./Card";
import CardDetails from "./CardDetails";

const data = [
	{
	  "id": 5731498,
	  "listing_url": "https://www.airbnb.com/rooms/5731498",
	  "scrape_id": 20150717184329,
	  "last_scraped": "2015-07-18",
	  "name": "A 2-bdrm house in Plaka of Athens",
	  "summary": "",
	  "space": "Ideally located a unique house in a very peaceful neighborhood of Plaka, near Acropolis. It is a traditional house in the heart of the historical center of Athens, in Plaka. The kitchen is fully equipped with oven, fridge with freezer. Cutlery, dishes and pans, kettle, espresso coffee maker (espresso capsules are provided), toaster. There is also a vacuum cleaner and a laundry machine. One big closet will make your stay more comfortable. Bed linen, towels and bath amenities are provided. Moreover, the apartment is fully airconditioned. The apartment is very close to a greek traditional tavernas, a pharmacy, banks and public transport.  Airport or any other transport is available upon demand at an additional but very reasonable cost.",
	  "description": "Ideally located a unique house in a very peaceful neighborhood of Plaka, near Acropolis. It is a traditional house in the heart of the historical center of Athens, in Plaka. The kitchen is fully equipped with oven, fridge with freezer. Cutlery, dishes and pans, kettle, espresso coffee maker (espresso capsules are provided), toaster. There is also a vacuum cleaner and a laundry machine. One big closet will make your stay more comfortable. Bed linen, towels and bath amenities are provided. Moreover, the apartment is fully airconditioned. The apartment is very close to a greek traditional tavernas, a pharmacy, banks and public transport.  Airport or any other transport is available upon demand at an additional but very reasonable cost.",
	  "experiences_offered": "none",
	  "neighborhood_overview": "",
	  "notes": "",
	  "transit": "",
	  "thumbnail_url": "https://a2.muscache.com/ac/pictures/71819787/97d77d9e_original.jpg?interpolation=lanczos-none&size=small&output-format=jpg&output-quality=70",
	  "medium_url": "https://a2.muscache.com/ac/pictures/71819787/97d77d9e_original.jpg?interpolation=lanczos-none&size=medium&output-format=jpg&output-quality=70",
	  "picture_url": "https://a2.muscache.com/ac/pictures/71819787/97d77d9e_original.jpg?interpolation=lanczos-none&size=large_cover&output-format=jpg&output-quality=70",
	  "xl_picture_url": "https://a2.muscache.com/ac/pictures/71819787/97d77d9e_original.jpg?interpolation=lanczos-none&size=x_large_cover&output-format=jpg&output-quality=70",
	  "host_id": 748818,
	  "host_url": "https://www.airbnb.com/users/show/748818",
	  "host_name": "George",
	  "host_since": "2011-06-27",
	  "host_location": "Athens, Attica, Greece",
	  "host_about": "I am very open character, I want to meet new people , I like cooking and hosting other people.",
	  "host_response_time": "within a few hours",
	  "host_response_rate": "89%",
	  "host_acceptance_rate": "97%",
	  "host_is_superhost": "f",
	  "host_thumbnail_url": "https://a1.muscache.com/ac/users/748818/profile_pic/1384667836/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=50:*&output-format=jpg&output-quality=70",
	  "host_picture_url": "https://a1.muscache.com/ac/users/748818/profile_pic/1384667836/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=225:*&output-format=jpg&output-quality=70",
	  "host_neighbourhood": "Kolonaki",
	  "host_listings_count": 130,
	  "host_total_listings_count": 130,
	  "host_verifications": "['email', 'phone', 'facebook', 'linkedin', 'reviews', 'jumio']",
	  "host_has_profile_pic": "t",
	  "host_identity_verified": "t",
	  "street": "Vyronos, Athina, 105 58, Greece",
	  "neighbourhood": "Plaka",
	  "neighbourhood_cleansed": "ΑΚΡΟΠΟΛΗ",
	  "neighbourhood_group_cleansed": "",
	  "city": "Athina",
	  "state": "",
	  "zipcode": "105 58",
	  "market": "Athens",
	  "country_code": "GR",
	  "country": "Greece",
	  "latitude": 37.96947012186602,
	  "longitude": 23.72908333747526,
	  "is_location_exact": "t",
	  "property_type": "Apartment",
	  "room_type": "Entire home/apt",
	  "accommodates": 5,
	  "bathrooms": 1,
	  "bedrooms": 2,
	  "beds": 3,
	  "bed_type": "Real Bed",
	  "amenities": "{TV,\"Cable TV\",Internet,\"Wireless Internet\",\"Air Conditioning\",Kitchen,Heating,\"Family/Kid Friendly\",Washer,Essentials,Shampoo}",
	  "square_feet": "",
	  "price": "$120.00",
	  "weekly_price": "",
	  "monthly_price": "",
	  "security_deposit": "$200.00",
	  "cleaning_fee": "$20.00",
	  "guests_included": 4,
	  "extra_people": "$15.00",
	  "minimum_nights": 2,
	  "maximum_nights": 1125,
	  "calendar_updated": "today",
	  "has_availability": "t",
	  "availability_30": 12,
	  "availability_60": 35,
	  "availability_90": 65,
	  "availability_365": 340,
	  "calendar_last_scraped": "2015-07-17",
	  "number_of_reviews": 16,
	  "first_review": "2015-04-07",
	  "last_review": "2015-07-15",
	  "review_scores_rating": 94,
	  "review_scores_accuracy": 9,
	  "review_scores_cleanliness": 10,
	  "review_scores_checkin": 10,
	  "review_scores_communication": 10,
	  "review_scores_location": 10,
	  "review_scores_value": 10,
	  "requires_license": "t",
	  "license": "",
	  "jurisdiction_names": "",
	  "instant_bookable": "t",
	  "cancellation_policy": "moderate",
	  "require_guest_profile_picture": "f",
	  "require_guest_phone_verification": "f",
	  "calculated_host_listings_count": 24,
	  "reviews_per_month": 4.66
	},
	{
	  "id": 1108690,
	  "listing_url": "https://www.airbnb.com/rooms/1108690",
	  "scrape_id": 20150717184329,
	  "last_scraped": "2015-07-18",
	  "name": "Just 200m from Acropolis, Athens",
	  "summary": "",
	  "space": "Sunny & Quiet apartment  at the first floor in a beauty full building. Just 100 meters from Acropolis & 30 meters from the Acropolis Musuem. Bedroom with double futon bed, a kitchen, wireless internet, landline and a confortable bathroom.  The flat is able to host up to 3 accommodates. Alll this just around the corner of the new Acropolis musuem.that leads to Plaka Area,Irodeion theatre and Thision. Plaka is the area under the stone hill of Acropolis full with restaurants which serve delicious traditional food. Erodeion is an ancient greek theatre where concerts and theater performances taking place. Thision area is also very close to the apartment.Thision is well known for its bars and restaurants.What is more, the area is very well connected not only with the center of the town but also with the sea. Metro Acropolis is only ! 50 meters from the flat.Buses and tram are also very close. If you have any questions,do not hesitate to contact me.",
	  "description": "Sunny & Quiet apartment  at the first floor in a beauty full building. Just 100 meters from Acropolis & 30 meters from the Acropolis Musuem. Bedroom with double futon bed, a kitchen, wireless internet, landline and a confortable bathroom.  The flat is able to host up to 3 accommodates. Alll this just around the corner of the new Acropolis musuem.that leads to Plaka Area,Irodeion theatre and Thision. Plaka is the area under the stone hill of Acropolis full with restaurants which serve delicious traditional food. Erodeion is an ancient greek theatre where concerts and theater performances taking place. Thision area is also very close to the apartment.Thision is well known for its bars and restaurants.What is more, the area is very well connected not only with the center of the town but also with the sea. Metro Acropolis is only ! 50 meters from the flat.Buses and tram are also very close. If you have any questions,do not hesitate to contact me.",
	  "experiences_offered": "none",
	  "neighborhood_overview": "",
	  "notes": "",
	  "transit": "",
	  "thumbnail_url": "https://a0.muscache.com/ac/pictures/19034905/6982ee6c_original.jpg?interpolation=lanczos-none&size=small&output-format=jpg&output-quality=70",
	  "medium_url": "https://a0.muscache.com/ac/pictures/19034905/6982ee6c_original.jpg?interpolation=lanczos-none&size=medium&output-format=jpg&output-quality=70",
	  "picture_url": "https://a0.muscache.com/ac/pictures/19034905/6982ee6c_original.jpg?interpolation=lanczos-none&size=large_cover&output-format=jpg&output-quality=70",
	  "xl_picture_url": "https://a0.muscache.com/ac/pictures/19034905/6982ee6c_original.jpg?interpolation=lanczos-none&size=x_large_cover&output-format=jpg&output-quality=70",
	  "host_id": 2436598,
	  "host_url": "https://www.airbnb.com/users/show/2436598",
	  "host_name": "Ektoras",
	  "host_since": "2012-05-22",
	  "host_location": "Athens, Attica, Greece",
	  "host_about": "I love music, shadow, sea , sports & the theater.",
	  "host_response_time": "within an hour",
	  "host_response_rate": "95%",
	  "host_acceptance_rate": "98%",
	  "host_is_superhost": "f",
	  "host_thumbnail_url": "https://a1.muscache.com/ac/users/2436598/profile_pic/1384177608/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=50:*&output-format=jpg&output-quality=70",
	  "host_picture_url": "https://a1.muscache.com/ac/users/2436598/profile_pic/1384177608/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=225:*&output-format=jpg&output-quality=70",
	  "host_neighbourhood": "",
	  "host_listings_count": 2,
	  "host_total_listings_count": 2,
	  "host_verifications": "['email', 'phone', 'reviews']",
	  "host_has_profile_pic": "t",
	  "host_identity_verified": "f",
	  "street": "Chatzichristou, Athens, Attica 117 42, Greece",
	  "neighbourhood": "",
	  "neighbourhood_cleansed": "ΑΚΡΟΠΟΛΗ",
	  "neighbourhood_group_cleansed": "",
	  "city": "Athens",
	  "state": "Attica",
	  "zipcode": "117 42",
	  "market": "Athens",
	  "country_code": "GR",
	  "country": "Greece",
	  "latitude": 37.968869919951636,
	  "longitude": 23.728969555787607,
	  "is_location_exact": "t",
	  "property_type": "Apartment",
	  "room_type": "Entire home/apt",
	  "accommodates": 2,
	  "bathrooms": 1,
	  "bedrooms": 1,
	  "beds": 1,
	  "bed_type": "Real Bed",
	  "amenities": "{Internet,\"Wireless Internet\",\"Air Conditioning\",Kitchen,\"Elevator in Building\",Heating,\"Family/Kid Friendly\",Essentials,Shampoo}",
	  "square_feet": "",
	  "price": "$42.00",
	  "weekly_price": "",
	  "monthly_price": "",
	  "security_deposit": "",
	  "cleaning_fee": "",
	  "guests_included": 1,
	  "extra_people": "$17.00",
	  "minimum_nights": 1,
	  "maximum_nights": 365,
	  "calendar_updated": "3 days ago",
	  "has_availability": "t",
	  "availability_30": 10,
	  "availability_60": 34,
	  "availability_90": 64,
	  "availability_365": 336,
	  "calendar_last_scraped": "2015-07-18",
	  "number_of_reviews": 189,
	  "first_review": "2013-05-15",
	  "last_review": "2015-07-13",
	  "review_scores_rating": 86,
	  "review_scores_accuracy": 9,
	  "review_scores_cleanliness": 8,
	  "review_scores_checkin": 9,
	  "review_scores_communication": 10,
	  "review_scores_location": 10,
	  "review_scores_value": 9,
	  "requires_license": "t",
	  "license": "",
	  "jurisdiction_names": "",
	  "instant_bookable": "f",
	  "cancellation_policy": "strict",
	  "require_guest_profile_picture": "t",
	  "require_guest_phone_verification": "t",
	  "calculated_host_listings_count": 2,
	  "reviews_per_month": 7.13
	},
	{
	  "id": 1286210,
	  "listing_url": "https://www.airbnb.com/rooms/1286210",
	  "scrape_id": 20150717184329,
	  "last_scraped": "2015-07-18",
	  "name": "Zen space near center of Athens",
	  "summary": "",
	  "space": "JUST REFURBISHED - BRAND NEW APARTMENT. Very earthly energy. It is situated on the ground floor of a building. So...a zen apartment near the center of Athens. It is situated only fourty minutes from Athens airport by metro (no change is required). Once you get off at the metro stop Ambelokipi, you walk  minutes and voila!!! Three metro stops more and you will find yourselves in the center of Athens.  Back to zen.....it is a one bedroom apartment with a small dinning room and a living room.  The main glass wall provides a unique lighting throughout the day. At night the street light gives an overall warm glow to the space. A kitchen door leads to a small courtyard. At night the courtyard lights give a depth to the entire space. There is a mini market open from 10am to 12 midnight which can accommodate all your needs. There is also an excellent restaurant nearby where one can enjoy a fine lunch or a relaxing dinner. A less pricy restaurant is situated just across the street.",
	  "description": "JUST REFURBISHED - BRAND NEW APARTMENT. Very earthly energy. It is situated on the ground floor of a building. So...a zen apartment near the center of Athens. It is situated only fourty minutes from Athens airport by metro (no change is required). Once you get off at the metro stop Ambelokipi, you walk  minutes and voila!!! Three metro stops more and you will find yourselves in the center of Athens.  Back to zen.....it is a one bedroom apartment with a small dinning room and a living room.  The main glass wall provides a unique lighting throughout the day. At night the street light gives an overall warm glow to the space. A kitchen door leads to a small courtyard. At night the courtyard lights give a depth to the entire space. There is a mini market open from 10am to 12 midnight which can accommodate all your needs. There is also an excellent restaurant nearby where one can enjoy a fine lunch or a relaxing dinner. A less pricy restaurant is situated just across the street.",
	  "experiences_offered": "none",
	  "neighborhood_overview": "",
	  "notes": "",
	  "transit": "",
	  "thumbnail_url": "https://a1.muscache.com/ac/pictures/19389554/a2ff7ebf_original.jpg?interpolation=lanczos-none&size=small&output-format=jpg&output-quality=70",
	  "medium_url": "https://a1.muscache.com/ac/pictures/19389554/a2ff7ebf_original.jpg?interpolation=lanczos-none&size=medium&output-format=jpg&output-quality=70",
	  "picture_url": "https://a1.muscache.com/ac/pictures/19389554/a2ff7ebf_original.jpg?interpolation=lanczos-none&size=large_cover&output-format=jpg&output-quality=70",
	  "xl_picture_url": "https://a1.muscache.com/ac/pictures/19389554/a2ff7ebf_original.jpg?interpolation=lanczos-none&size=x_large_cover&output-format=jpg&output-quality=70",
	  "host_id": 372161,
	  "host_url": "https://www.airbnb.com/users/show/372161",
	  "host_name": "Peter",
	  "host_since": "2011-02-01",
	  "host_location": "Athens, Attica, Greece",
	  "host_about": "Filmmaker and musician who loves to walk Athens. Currently enjoying a hot summer after a demanding short film. Please visit my website to know more about me.\n(website hidden)",
	  "host_response_time": "a few days or more",
	  "host_response_rate": "33%",
	  "host_acceptance_rate": "100%",
	  "host_is_superhost": "f",
	  "host_thumbnail_url": "https://a2.muscache.com/ac/users/372161/profile_pic/1296594728/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=50:*&output-format=jpg&output-quality=70",
	  "host_picture_url": "https://a2.muscache.com/ac/users/372161/profile_pic/1296594728/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=225:*&output-format=jpg&output-quality=70",
	  "host_neighbourhood": "",
	  "host_listings_count": 1,
	  "host_total_listings_count": 1,
	  "host_verifications": "['email', 'facebook', 'reviews']",
	  "host_has_profile_pic": "t",
	  "host_identity_verified": "f",
	  "street": "Vatheos, Athens, Attica 115 22, Greece",
	  "neighbourhood": "",
	  "neighbourhood_cleansed": "ΑΜΠΕΛΟΚΗΠΟΙ",
	  "neighbourhood_group_cleansed": "",
	  "city": "Athens",
	  "state": "Attica",
	  "zipcode": "115 22",
	  "market": "Athens",
	  "country_code": "GR",
	  "country": "Greece",
	  "latitude": 37.989954745633725,
	  "longitude": 23.758910281603455,
	  "is_location_exact": "t",
	  "property_type": "Apartment",
	  "room_type": "Entire home/apt",
	  "accommodates": 2,
	  "bathrooms": 1,
	  "bedrooms": 1,
	  "beds": 1,
	  "bed_type": "Real Bed",
	  "amenities": "{\"Wireless Internet\",Kitchen,\"Pets Allowed\",Heating,\"Family/Kid Friendly\",Washer}",
	  "square_feet": "",
	  "price": "$48.00",
	  "weekly_price": "$250.00",
	  "monthly_price": "$560.00",
	  "security_deposit": "",
	  "cleaning_fee": "$10.00",
	  "guests_included": 1,
	  "extra_people": "$0.00",
	  "minimum_nights": 1,
	  "maximum_nights": 1125,
	  "calendar_updated": "6 weeks ago",
	  "has_availability": "t",
	  "availability_30": 11,
	  "availability_60": 41,
	  "availability_90": 71,
	  "availability_365": 346,
	  "calendar_last_scraped": "2015-07-17",
	  "number_of_reviews": 4,
	  "first_review": "2013-12-14",
	  "last_review": "2015-07-05",
	  "review_scores_rating": 100,
	  "review_scores_accuracy": 10,
	  "review_scores_cleanliness": 10,
	  "review_scores_checkin": 10,
	  "review_scores_communication": 10,
	  "review_scores_location": 10,
	  "review_scores_value": 10,
	  "requires_license": "t",
	  "license": "",
	  "jurisdiction_names": "",
	  "instant_bookable": "f",
	  "cancellation_policy": "moderate",
	  "require_guest_profile_picture": "f",
	  "require_guest_phone_verification": "f",
	  "calculated_host_listings_count": 1,
	  "reviews_per_month": 0.21
	},
	{
	  "id": 918812,
	  "listing_url": "https://www.airbnb.com/rooms/918812",
	  "scrape_id": 20150717184329,
	  "last_scraped": "2015-07-18",
	  "name": "Athens Soul Apartments Plaka",
	  "summary": "",
	  "space": "This 30m2 flat on Frinihou str. is located in Plaka, the old part of the city, at the foot of the Acropolis in the heart of Athens. Frinihou str. is a quiet street very close to a main street which leads to the New Acropolis Museum. The flat is only 100m away from the “Acropolis” Metro station as well as the New Acropolis Museum. Very close -less than 50m away- the Dionisiou Aeropagitou pedestrian street starts which is considered one of the most beautiful pedestrian streets in Athens. It takes straight to the Herodou Attikou ancient theatre. The flat is in the semi-basement of a stately building with its own court aglaise. It overlooks the street and its really sunny and bright. The flat is fully furnished, beautifully decorated and equipped with a kitchen , air-conditioning , central heating, a telephone line and free Internet. It is a two person flat but there is plenty of room for a third person. Super offer Two bicycles at your disposal, to ride the historical part of Athens free",
	  "description": "This 30m2 flat on Frinihou str. is located in Plaka, the old part of the city, at the foot of the Acropolis in the heart of Athens. Frinihou str. is a quiet street very close to a main street which leads to the New Acropolis Museum. The flat is only 100m away from the “Acropolis” Metro station as well as the New Acropolis Museum. Very close -less than 50m away- the Dionisiou Aeropagitou pedestrian street starts which is considered one of the most beautiful pedestrian streets in Athens. It takes straight to the Herodou Attikou ancient theatre. The flat is in the semi-basement of a stately building with its own court aglaise. It overlooks the street and its really sunny and bright. The flat is fully furnished, beautifully decorated and equipped with a kitchen , air-conditioning , central heating, a telephone line and free Internet. It is a two person flat but there is plenty of room for a third person. Super offer Two bicycles at your disposal, to ride the historical part of Athens free",
	  "experiences_offered": "none",
	  "neighborhood_overview": "",
	  "notes": "",
	  "transit": "",
	  "thumbnail_url": "https://a1.muscache.com/ac/pictures/13462809/26642ff7_original.jpg?interpolation=lanczos-none&size=small&output-format=jpg&output-quality=70",
	  "medium_url": "https://a1.muscache.com/ac/pictures/13462809/26642ff7_original.jpg?interpolation=lanczos-none&size=medium&output-format=jpg&output-quality=70",
	  "picture_url": "https://a1.muscache.com/ac/pictures/13462809/26642ff7_original.jpg?interpolation=lanczos-none&size=large_cover&output-format=jpg&output-quality=70",
	  "xl_picture_url": "https://a1.muscache.com/ac/pictures/13462809/26642ff7_original.jpg?interpolation=lanczos-none&size=x_large_cover&output-format=jpg&output-quality=70",
	  "host_id": 4935030,
	  "host_url": "https://www.airbnb.com/users/show/4935030",
	  "host_name": "Dimitris",
	  "host_since": "2013-02-02",
	  "host_location": "Athens, Attica, Greece",
	  "host_about": "Hello! My name is Dimitris. You are welcome to come and stay at my apartments in Athens, Greece! If you have any questions, feel free to ask!",
	  "host_response_time": "within a few hours",
	  "host_response_rate": "100%",
	  "host_acceptance_rate": "100%",
	  "host_is_superhost": "f",
	  "host_thumbnail_url": "https://a0.muscache.com/ac/users/4935030/profile_pic/1359790474/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=50:*&output-format=jpg&output-quality=70",
	  "host_picture_url": "https://a0.muscache.com/ac/users/4935030/profile_pic/1359790474/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=225:*&output-format=jpg&output-quality=70",
	  "host_neighbourhood": "",
	  "host_listings_count": 2,
	  "host_total_listings_count": 2,
	  "host_verifications": "['email', 'phone', 'facebook', 'linkedin', 'reviews', 'jumio']",
	  "host_has_profile_pic": "t",
	  "host_identity_verified": "t",
	  "street": "Frinichou, Athens, Attica 105 58, Greece",
	  "neighbourhood": "",
	  "neighbourhood_cleansed": "ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ",
	  "neighbourhood_group_cleansed": "",
	  "city": "Athens",
	  "state": "Attica",
	  "zipcode": "105 58",
	  "market": "Athens",
	  "country_code": "GR",
	  "country": "Greece",
	  "latitude": 37.969859435055255,
	  "longitude": 23.731203858464916,
	  "is_location_exact": "t",
	  "property_type": "Apartment",
	  "room_type": "Entire home/apt",
	  "accommodates": 2,
	  "bathrooms": 1,
	  "bedrooms": 1,
	  "beds": 1,
	  "bed_type": "Real Bed",
	  "amenities": "{Internet,\"Wireless Internet\",\"Air Conditioning\",Kitchen,Heating}",
	  "square_feet": 323,
	  "price": "$40.00",
	  "weekly_price": "",
	  "monthly_price": "",
	  "security_deposit": "",
	  "cleaning_fee": "$10.00",
	  "guests_included": 1,
	  "extra_people": "$0.00",
	  "minimum_nights": 3,
	  "maximum_nights": 60,
	  "calendar_updated": "3 weeks ago",
	  "has_availability": "t",
	  "availability_30": 4,
	  "availability_60": 7,
	  "availability_90": 12,
	  "availability_365": 224,
	  "calendar_last_scraped": "2015-07-18",
	  "number_of_reviews": 102,
	  "first_review": "2013-03-25",
	  "last_review": "2015-07-05",
	  "review_scores_rating": 95,
	  "review_scores_accuracy": 10,
	  "review_scores_cleanliness": 9,
	  "review_scores_checkin": 10,
	  "review_scores_communication": 10,
	  "review_scores_location": 10,
	  "review_scores_value": 10,
	  "requires_license": "t",
	  "license": "",
	  "jurisdiction_names": "",
	  "instant_bookable": "f",
	  "cancellation_policy": "moderate",
	  "require_guest_profile_picture": "f",
	  "require_guest_phone_verification": "t",
	  "calculated_host_listings_count": 2,
	  "reviews_per_month": 3.62
	},
	{
	  "id": 240960,
	  "listing_url": "https://www.airbnb.com/rooms/240960",
	  "scrape_id": 20150717184329,
	  "last_scraped": "2015-07-18",
	  "name": "ATHENS DESIGNER'S LOFT DOWNTOWN",
	  "summary": "",
	  "space": "Designer's down town loft, constructed by an architect, more than once published in architectural magazines (like 'House & Garden', 'Maison & Decoration', etc.). Fully equipped with high tech devices - 2 flat screen 40' and 60' TV, home cinema Wi-Fi, fully air condition. Central Psyri Square view, sunset view, extremely luminous place. A down town loft in the most convenient area of Psyri which has archaeological as well as cosmopolitan and urban value.  \"monastiraki\" metro station with direct itinerary to/from the airport is in Walking distance (approx. 2 min.)  from the Acropolis and historic area of Thisseion and Plaka. Walking distance (approx. 12 min)  from Gazi area, famous for it's alternative night-life and clubbing. Walking distance (approx. 15 min) from Kolonaki area, the best market and shopping centre. One big bedroom with a 2.00x2.00m bed And a very big sofa for 2-3 persons. Full equipped bathroom with 2 access from the living room and from the bedroom. If you have any mor",
	  "description": "Designer's down town loft, constructed by an architect, more than once published in architectural magazines (like 'House & Garden', 'Maison & Decoration', etc.). Fully equipped with high tech devices - 2 flat screen 40' and 60' TV, home cinema Wi-Fi, fully air condition. Central Psyri Square view, sunset view, extremely luminous place. A down town loft in the most convenient area of Psyri which has archaeological as well as cosmopolitan and urban value.  \"monastiraki\" metro station with direct itinerary to/from the airport is in Walking distance (approx. 2 min.)  from the Acropolis and historic area of Thisseion and Plaka. Walking distance (approx. 12 min)  from Gazi area, famous for it's alternative night-life and clubbing. Walking distance (approx. 15 min) from Kolonaki area, the best market and shopping centre. One big bedroom with a 2.00x2.00m bed And a very big sofa for 2-3 persons. Full equipped bathroom with 2 access from the living room and from the bedroom. If you have any mor",
	  "experiences_offered": "none",
	  "neighborhood_overview": "",
	  "notes": "",
	  "transit": "metro station MONASTIRAKI.",
	  "thumbnail_url": "https://a2.muscache.com/ac/pictures/2261709/e6e849e7_original.jpg?interpolation=lanczos-none&size=small&output-format=jpg&output-quality=70",
	  "medium_url": "https://a2.muscache.com/ac/pictures/2261709/e6e849e7_original.jpg?interpolation=lanczos-none&size=medium&output-format=jpg&output-quality=70",
	  "picture_url": "https://a2.muscache.com/ac/pictures/2261709/e6e849e7_original.jpg?interpolation=lanczos-none&size=large_cover&output-format=jpg&output-quality=70",
	  "xl_picture_url": "https://a2.muscache.com/ac/pictures/2261709/e6e849e7_original.jpg?interpolation=lanczos-none&size=x_large_cover&output-format=jpg&output-quality=70",
	  "host_id": 1264236,
	  "host_url": "https://www.airbnb.com/users/show/1264236",
	  "host_name": "Ioannis",
	  "host_since": "2011-10-08",
	  "host_location": "Athens, Attica, Greece",
	  "host_about": "Ioannis is an architect-designer and owner of  the 'Minnie The Moocher' Bar in Athens . If you have any questions, feel free to ask!",
	  "host_response_time": "within a few hours",
	  "host_response_rate": "100%",
	  "host_acceptance_rate": "100%",
	  "host_is_superhost": "f",
	  "host_thumbnail_url": "https://a2.muscache.com/ac/users/1264236/profile_pic/1366370963/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=50:*&output-format=jpg&output-quality=70",
	  "host_picture_url": "https://a2.muscache.com/ac/users/1264236/profile_pic/1366370963/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=225:*&output-format=jpg&output-quality=70",
	  "host_neighbourhood": "Psyri",
	  "host_listings_count": 1,
	  "host_total_listings_count": 1,
	  "host_verifications": "['email', 'phone', 'facebook', 'reviews', 'jumio']",
	  "host_has_profile_pic": "t",
	  "host_identity_verified": "t",
	  "street": "Pallados, Athens, Attica 105 54, Greece",
	  "neighbourhood": "Psyri",
	  "neighbourhood_cleansed": "ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ",
	  "neighbourhood_group_cleansed": "",
	  "city": "Athens",
	  "state": "Attica",
	  "zipcode": "105 54",
	  "market": "Athens",
	  "country_code": "GR",
	  "country": "Greece",
	  "latitude": 37.9795231980909,
	  "longitude": 23.723668102859826,
	  "is_location_exact": "t",
	  "property_type": "Apartment",
	  "room_type": "Entire home/apt",
	  "accommodates": 4,
	  "bathrooms": 1,
	  "bedrooms": 1,
	  "beds": 1,
	  "bed_type": "Real Bed",
	  "amenities": "{TV,\"Cable TV\",Internet,\"Wireless Internet\",\"Air Conditioning\",Kitchen,\"Smoking Allowed\",\"Pets Allowed\",\"Pets live on this property\",Cat(s),\"Elevator in Building\",\"Buzzer/Wireless Intercom\",Heating,\"Suitable for Events\",\"Fire Extinguisher\",Essentials,Shampoo}",
	  "square_feet": "",
	  "price": "$70.00",
	  "weekly_price": "$450.00",
	  "monthly_price": "$1,300.00",
	  "security_deposit": "$200.00",
	  "cleaning_fee": "$30.00",
	  "guests_included": 2,
	  "extra_people": "$10.00",
	  "minimum_nights": 2,
	  "maximum_nights": 60,
	  "calendar_updated": "yesterday",
	  "has_availability": "t",
	  "availability_30": 24,
	  "availability_60": 54,
	  "availability_90": 84,
	  "availability_365": 359,
	  "calendar_last_scraped": "2015-07-18",
	  "number_of_reviews": 22,
	  "first_review": "2012-10-09",
	  "last_review": "2015-05-16",
	  "review_scores_rating": 98,
	  "review_scores_accuracy": 10,
	  "review_scores_cleanliness": 10,
	  "review_scores_checkin": 10,
	  "review_scores_communication": 10,
	  "review_scores_location": 10,
	  "review_scores_value": 10,
	  "requires_license": "t",
	  "license": "",
	  "jurisdiction_names": "",
	  "instant_bookable": "f",
	  "cancellation_policy": "strict",
	  "require_guest_profile_picture": "f",
	  "require_guest_phone_verification": "f",
	  "calculated_host_listings_count": 1,
	  "reviews_per_month": 0.65
	},
	{
	  "id": 587782,
	  "listing_url": "https://www.airbnb.com/rooms/587782",
	  "scrape_id": 20150717184329,
	  "last_scraped": "2015-07-18",
	  "name": "Breath Away National Garden wifi",
	  "summary": "",
	  "space": "A breath away from  Zappeion and the National Royal Garden  just a few seconds away . There are supermarkets, stores, restaurants, caffes, banks and pharmacies within a 2min. walking . Fully Furnished Studio on the 1st  floor  ,28.00 square meters including:1 spacious area, full bath with shower and fully equipped small kitchen. Studio amenities include: Hot water, Flat LCD  TV, Hair dryer,Iron, Cooking facilities,  air-conditioning , Washing Machine, Coffee maker, Toaster, Kettler,Refrigerator, Micro Wave, Oven. kitchen accessories (plates, dishes, pots, ventilation, etc). It also includes: 1 double bed with all necessary accessories (linens, pillows, etc) High speed internet is provided free For the benefit of all guests: No pets and No Smoking",
	  "description": "A breath away from  Zappeion and the National Royal Garden  just a few seconds away . There are supermarkets, stores, restaurants, caffes, banks and pharmacies within a 2min. walking . Fully Furnished Studio on the 1st  floor  ,28.00 square meters including:1 spacious area, full bath with shower and fully equipped small kitchen. Studio amenities include: Hot water, Flat LCD  TV, Hair dryer,Iron, Cooking facilities,  air-conditioning , Washing Machine, Coffee maker, Toaster, Kettler,Refrigerator, Micro Wave, Oven. kitchen accessories (plates, dishes, pots, ventilation, etc). It also includes: 1 double bed with all necessary accessories (linens, pillows, etc) High speed internet is provided free For the benefit of all guests: No pets and No Smoking",
	  "experiences_offered": "none",
	  "neighborhood_overview": "",
	  "notes": "",
	  "transit": "",
	  "thumbnail_url": "https://a0.muscache.com/ac/pictures/57865371/e2003c3f_original.jpg?interpolation=lanczos-none&size=small&output-format=jpg&output-quality=70",
	  "medium_url": "https://a0.muscache.com/ac/pictures/57865371/e2003c3f_original.jpg?interpolation=lanczos-none&size=medium&output-format=jpg&output-quality=70",
	  "picture_url": "https://a0.muscache.com/ac/pictures/57865371/e2003c3f_original.jpg?interpolation=lanczos-none&size=large_cover&output-format=jpg&output-quality=70",
	  "xl_picture_url": "https://a0.muscache.com/ac/pictures/57865371/e2003c3f_original.jpg?interpolation=lanczos-none&size=x_large_cover&output-format=jpg&output-quality=70",
	  "host_id": 172333,
	  "host_url": "https://www.airbnb.com/users/show/172333",
	  "host_name": "Athens",
	  "host_since": "2010-07-19",
	  "host_location": "Athens, Attica, Greece",
	  "host_about": "Whether you come to Athens as a tourist or for professional reasons our rental apartments are suitable in the best way for your short or long-term accommodation!",
	  "host_response_time": "within an hour",
	  "host_response_rate": "100%",
	  "host_acceptance_rate": "100%",
	  "host_is_superhost": "f",
	  "host_thumbnail_url": "https://a1.muscache.com/ac/users/172333/profile_pic/1402758728/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=50:*&output-format=jpg&output-quality=70",
	  "host_picture_url": "https://a1.muscache.com/ac/users/172333/profile_pic/1402758728/original.jpg?interpolation=lanczos-none&crop=w:w;*,*&crop=h:h;*,*&resize=225:*&output-format=jpg&output-quality=70",
	  "host_neighbourhood": "Plaka",
	  "host_listings_count": 4,
	  "host_total_listings_count": 4,
	  "host_verifications": "['email', 'phone', 'facebook', 'reviews']",
	  "host_has_profile_pic": "t",
	  "host_identity_verified": "f",
	  "street": "Voulis, Athens, 105 62, Greece",
	  "neighbourhood": "Plaka",
	  "neighbourhood_cleansed": "ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ",
	  "neighbourhood_group_cleansed": "",
	  "city": "Athens",
	  "state": "",
	  "zipcode": "105 62",
	  "market": "Athens",
	  "country_code": "GR",
	  "country": "Greece",
	  "latitude": 37.97657578746484,
	  "longitude": 23.733037667962027,
	  "is_location_exact": "t",
	  "property_type": "Apartment",
	  "room_type": "Entire home/apt",
	  "accommodates": 2,
	  "bathrooms": 1,
	  "bedrooms": 1,
	  "beds": 1,
	  "bed_type": "Real Bed",
	  "amenities": "{TV,Internet,\"Wireless Internet\",\"Air Conditioning\",Kitchen,\"Elevator in Building\",Heating,Washer}",
	  "square_feet": "",
	  "price": "$40.00",
	  "weekly_price": "$260.00",
	  "monthly_price": "$550.00",
	  "security_deposit": "$90.00",
	  "cleaning_fee": "$20.00",
	  "guests_included": 1,
	  "extra_people": "$0.00",
	  "minimum_nights": 3,
	  "maximum_nights": 1125,
	  "calendar_updated": "today",
	  "has_availability": "t",
	  "availability_30": 16,
	  "availability_60": 34,
	  "availability_90": 61,
	  "availability_365": 336,
	  "calendar_last_scraped": "2015-07-18",
	  "number_of_reviews": 15,
	  "first_review": "2013-01-05",
	  "last_review": "2015-06-22",
	  "review_scores_rating": 83,
	  "review_scores_accuracy": 9,
	  "review_scores_cleanliness": 8,
	  "review_scores_checkin": 8,
	  "review_scores_communication": 9,
	  "review_scores_location": 10,
	  "review_scores_value": 9,
	  "requires_license": "t",
	  "license": "",
	  "jurisdiction_names": "",
	  "instant_bookable": "f",
	  "cancellation_policy": "flexible",
	  "require_guest_profile_picture": "t",
	  "require_guest_phone_verification": "t",
	  "calculated_host_listings_count": 4,
	  "reviews_per_month": 0.49
	}
  ];

const Cards = () => (
	<div className="flex flex-wrap">
		{data.map(({thumbnail_url, medium_url, price, room_type, beds, number_of_reviews, review_scores_rating,street, description }, id) => (
			<Card key={id} id={id} thumbnail_url={thumbnail_url} medium_url={medium_url} price={price} room_type={room_type} beds={beds} number_of_reviews={number_of_reviews} review_scores_rating={review_scores_rating} street={street} description={description}/>
		))}
	</div>
);

export default Cards;

